{{- if .Values.ingressGateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiae
  namespace: kiae-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts: {{ .Values.ingressGateway.hosts }}
      {{- if .Values.ingressGateway.credentialName -}}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.ingressGateway.credentialName}}
      {{- end }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiae
  namespace: kiae-system
spec:
  hosts:
    - "*"
  gateways:
    - kiae
  http:
    - route:
        - destination:
            host: kiae
            port:
              number: 8081
{{- end }}