apiVersion: v1
kind: ConfigMap
metadata:
  name: kiae
  namespace: kiae-system
data:
  config.yaml: |
    debug: true

    server:
      port: 8024

    mongodb:
      dsn: {{ .Values.config.mongodb.dsn }}
      database: {{ .Values.config.mongodb.database }}

    oidc:
      issuer: {{ .Values.config.server.url }}/proxies/dex
      clientID: {{ .Values.config.dex.clientID }}
      clientSecret: {{ .Values.config.dex.clientSecret }}

    dex:
      endpoint: {{ .Values.config.dex.endpoint }}

    loki:
      endpoint: {{ .Values.config.loki.endpoint }}
