apiVersion: v1
kind: Secret
metadata:
  name: kiae-dex
  namespace: kiae-system
type: Opaque
stringData:
  config.yaml: |
    issuer: {{ .Values.config.server.url }}/proxies/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    connectors: {{ .Values.config.dex.connectors | toJson }}
    oauth2:
      skipApprovalScreen: true

    staticClients:
      - id: {{ .Values.config.dex.clientID }}
        secret: {{ .Values.config.dex.clientSecret }}
        name: Kiae
        redirectURIs:
          - '{{ .Values.config.server.url }}/oauth2/callback'

    enablePasswordDB: true
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"