apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builds.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Image
      type: string
      jsonPath: .status.latestImage
    - name: Succeeded
      type: string
      jsonPath: .status.conditions[?(@.type=="Succeeded")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Image
      type: string
      jsonPath: .status.latestImage
    - name: Succeeded
      type: string
      jsonPath: .status.conditions[?(@.type=="Succeeded")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  names:
    kind: Build
    listKind: BuildList
    singular: build
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    - blds
    categories:
    - kpack
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builders.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  names:
    kind: Builder
    listKind: BuilderList
    singular: builder
    plural: builders
    shortNames:
    - bldr
    - bldrs
    categories:
    - kpack
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  names:
    kind: ClusterBuilder
    listKind: ClusterBuilderList
    singular: clusterbuilder
    plural: clusterbuilders
    shortNames:
    - clstbldr
    - clstbldrs
    categories:
    - kpack
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstacks.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  names:
    kind: ClusterStack
    listKind: ClusterStackList
    singular: clusterstack
    plural: clusterstacks
    categories:
    - kpack
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstores.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
    subresources:
      status: {}
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
    subresources:
      status: {}
  names:
    kind: ClusterStore
    listKind: ClusterStoreList
    singular: clusterstore
    plural: clusterstores
    categories:
    - kpack
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sourceresolvers.kpack.io
spec:
  group: kpack.io
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kiae-system
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
  names:
    kind: SourceResolver
    listKind: SourceResolverList
    singular: sourceresolver
    plural: sourceresolvers
    categories:
      - kpack
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.kpack.io
spec:
  group: kpack.io
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: LatestImage
          type: string
          jsonPath: .status.latestImage
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: LatestImage
          type: string
          jsonPath: .status.latestImage
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kiae-system
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
  names:
    kind: Image
    listKind: ImageList
    singular: image
    plural: images
    shortNames:
      - cnbimage
      - cnbimages
      - img
      - imgs
    categories:
      - kpack
  scope: Namespaced